### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Mar3xgg** [mortuusars/Wares#22]
server crash when using latest version of mod (1.2.5) in version 1.19.2 in modpack Create: Prepare to Dye; posting here in case this is a fix needed to be applied on your end, as it's implied this mod doesn't work on servers as per the line referring to invalid dist: dedicated server

[message.txt](https://github.com/mortuusars/Wares/files/13998027/message.txt)

**Comment by mortuusars** [comment]
This is an error in Ptdye mod. They reference client code in the main class, which makes it fail on server.
