### ISSUE TITLE
Game/Server crash and world lock when Packager above Level 5 reaches the end of the delivery progress

### ISSUE THREAD

**Issue by FlamesTM** [mortuusars/Wares#27]
If a Packager above Level 5 (6 and 99 tested) uses the Delivery Table to speed up the progress on an Agreement, when the progress bar reaches the end, it will crash the game and permanently lock the world unless you reset the chunk where the Delivery Table is, or find a way to remove the Delivery Table.

This happens on both 1.19.2, and 1.20.1 on the latest version of the mod.

[crash-2024-09-15_18.05.38-server.txt](https://github.com/user-attachments/files/17006629/crash-2024-09-15_18.05.38-server.txt)

**Comment by mortuusars** [comment]
How levels above 5 are obtained? Is it only for commands/creative mode? Or other mod allows levels greater than 5?

**Comment by FlamesTM** [comment]
You can use commands to get levels above 5 on Villagers which will hide their rank in the trading GUI
