### ISSUE TITLE
Inventory appears empty while in the box ui

### ISSUE THREAD

**Issue by Manimanocas** [mortuusars/Wares#7]
The inventory appears empty while you are packaging a box
![2023-09-29_00 08 01](https://github.com/mortuusars/Wares/assets/42978255/e7828b1e-8424-41ff-8b38-c654ea944523)
![2023-09-29_00 08 04](https://github.com/mortuusars/Wares/assets/42978255/09ab16d9-fc3b-4977-a2eb-0b3a46caa70f)
[modlist.txt](https://github.com/mortuusars/Wares/files/12754516/modlist.txt)

**Comment by mortuusars** [comment]
Does it happen when only Wares is loaded? (without other mods)
If without others it works fine - you can find the conflicting mod by removing mods until issue disappears.

Also make sure you are using latest version of the mod.

**Comment by Manimanocas** [comment]
> Does it happen when only Wares is loaded? (without other mods) If without others it works fine - you can find the conflicting mod by removing mods until issue disappears.


found the mod, the issue happens when I have create installed. The issue happens with 0.5.1.e and the previous version.

**Comment by mortuusars** [comment]
![image](https://github.com/mortuusars/Wares/assets/65141267/de6a9003-051e-48a6-abf1-2184c2a6d1f7)
MC 1.19.2, Create 0.5.1e, Wares 1.2.0
Works fine on my end.

**Comment by Manimanocas** [comment]
Weird, I am 100% sure this happens to me with create heres some photos:
![2023-10-01_01 37 27](https://github.com/mortuusars/Wares/assets/42978255/865cbfe1-061f-43a4-95e5-60334b1ce351)
![2023-10-01_01 37 29](https://github.com/mortuusars/Wares/assets/42978255/7d3d07f6-6776-470f-bd31-a1e3ff9aee3b)
![2023-10-01_01 37 34](https://github.com/mortuusars/Wares/assets/42978255/c142abec-4f16-4fc3-80f4-217bf37a0cca)

**Comment by Manimanocas** [comment]
Ok a weird update, it only happens in old worlds
I cant find the correlation, if you know a way I can narrow this down plz tell me
If you want the saves here they are, 8 is bugged 9 should be normal
https://drive.google.com/file/d/1SrGia_6LOobwQamO1rEKgf1RgA_bDcv9/view?usp=sharing

**Comment by mortuusars** [comment]
Found the issue - due to the oversight in screen slot creation, it would skip creating inventory slots if cardboard box was in hotbar slot 7 specifically. Will be fixed in next release.
Thanks for reporting and providing the saves.
