### ISSUE TITLE
nbt data not working

### ISSUE THREAD

**Issue by Yarden-zamir** [mortuusars/Wares#8]
the command
```
/give @s wares:delivery_agreement{title:'{"text":"A Great Deal"}',requestedItems:[{id:"minecraft:emerald", Count: 4, display:{Name:'{"translate":"item.minecraft.diamond"}'}}],paymentItems:[{id:"minecraft:emerald",Count:1}],ordered:10}
```
gives me an agreement with regular emeralds

**Comment by mortuusars** [comment]
`display` should be defined inside the `tag`:
`/give @s wares:delivery_agreement{title:'{"text":"A Great Deal"}',requestedItems:[{id:"minecraft:emerald", Count: 4, tag:{display:{Name:'{"translate":"item.minecraft.diamond"}'}}}],paymentItems:[{id:"minecraft:emerald",Count:1}],ordered:10}`

**Comment by Yarden-zamir** [comment]
Ah i see, I followed the example here https://github.com/mortuusars/Wares/wiki/Delivery-Agreement#examples

Thank you

**Comment by mortuusars** [comment]
I've fixed the example. Thanks.

**Comment by Yarden-zamir** [comment]
sidenote, it's anoying that github wikis don't have an edit button at the top to make a pr like code has, feels like it should lol
