### ISSUE TITLE
[request] Keep the delivery agreement's title when it transitions between states

### ISSUE THREAD

**Issue by Yarden-zamir** [mortuusars/Wares#9]
I want to name my sealed agreement, give it a recipe, then use the completed agreement in another recipe. Right now they all look and read the same though

**Comment by Yarden-zamir** [comment]
<img width="300" alt="Screen Shot 2023-11-08 at 0 57 54" src="https://github.com/mortuusars/Wares/assets/8178413/9111c8d9-a7e9-404a-8392-9b2b8c4c26eb">

**Comment by mortuusars** [comment]
Please explain in more detail what you want to do. The title and the message are a bit contradicting each other, or maybe I didn't understand correctly.

**Comment by Yarden-zamir** [comment]
Right now a sealed agreement, when opened ignores nbt values that are not related to the wares mod when building the resulting agreement. Which makes sense, but i causes an issue where the player can't diffreciet agreements in recipes where they can't right click to view details

**Comment by Yarden-zamir** [comment]
Right now my solution is to use agreements instead of sealed agreements because those keep their extra nbt (like name) after becoming completed. Not perfect because I can't use loot tables hence the request

**Comment by mortuusars** [comment]
Added in 1.2.2.

**Comment by Yarden-zamir** [comment]
Awesome, thank you!
